export const CONTROLLER = {
    USER: Symbol.for('USER_CONTROLLER'),
    AUTH: Symbol.for('AUTH_CONTROLLER'),
    CATEGORY: Symbol.for('CATEGORY_CONTROLLER'),
    ATTRIBUTE: Symbol.for('ATTRIBUTE_CONTROLLER'),
    PRODUCT_ATTRIBUTE: Symbol.for('PRODUCT_ATTRIBUTE_CONTROLLER'),
    PRODUCT_CATEGORY: Symbol.for('PRODUCT_CATEGORY_CONTROLLER')
}

