export const TYPES = {
    CONTROLLER: Symbol.for('CONTROLLER'),
    SEQUELIZE: Symbol.for('SEQUELIZE'),
    TABLE: Symbol.for('TABLE'),
    APPLICATION: Symbol.for('APPLICATION'),
    ROUTER: Symbol.for('ROUTER'),
    MIDDLEWARE: Symbol.for('MIDDLEWARE'),
    CONFIG: Symbol.for('CONFIG'),
    LOGGER: Symbol.for('LOGGER'),
    HTTP: Symbol.for('HTTP'),
    API: Symbol.for('API'),
    ARRAY_HELPER: Symbol.for('ARRAY_HELPER'),
    JWT_HELPER: Symbol.for('JWT_HELPER'),
    OBJECT_HELPER: Symbol.for('OBJECT_HELPER'),
    HTTP_HELPER: Symbol.for('HTTP_HELPER'),
    PARSER: Symbol.for('PARSER'),
    HTTP_CONTEXT: Symbol.for('HTTP_CONTEXT'),
    QUERY_PARSER: Symbol.for('QUERY_PARSER'),
    FACTORY: Symbol.for('FACTORY')
}